### PR TITLE
Fix issues when removing some vehicle properties

### PR DESCRIPTION
**Pull request by alexander-schilling**
There are some issues with esx_lscustom, when you hover on turbo or xenon (and I think smoke), they are applied but not removed, this fixed it for me. This should also work if you want to remove those properties from the vehicle.

### CODE REVIEW

**Comment by FBFezz** [comment]
https://github.com/ESX-Org/esx_lscustom/pull/93

**Comment by alexander-schilling** [comment]
> 
> 
> [ESX-Org/esx_lscustom#93](https://github.com/ESX-Org/esx_lscustom/pull/93)

I believe that the pull that you mention wouldn't work if you don't pass the argument modTurbo and modXenon, because of the _not nil_ equals true, it would remove the property even when you don't want to remove it.

**Comment by FBFezz** [comment]
idk i just remember looking at it i haven't tried it out really

**Review by yagizher — APPROVED** [review]

**Comment by namikoglu** [comment]
This pr is about vehicle properties, please revert the last changes and open another pr

**Comment by Neddings** [comment]
@alexander-schilling Using elseif's in those places would make the code a little wobbly. Also I think it's more important that LSCustoms updates their script then EXM having to change their Vehicle properties.

**Comment by HellraiserTwo** [comment]
Done, sir! :)

**Review by jaymo1011 — APPROVED** [review]

**Pull request merged**
