### PR TITLE
fix (server ) - add/remove permissions

### PR DESCRIPTION
**Pull request by benzon**

### CODE REVIEW

**Comment by nathanctech** [comment]
This change was already applied in c388d2f.

**Comment by benzon** [comment]
Nooope :) only on one line not all so nope check once again please.

**Comment by benzon** [comment]
> This change was already applied in [c388d2f](https://github.com/extendedmode/extendedmode/commit/c388d2feaded87a381263daf967af423fd1d2c24).

Line 18 was changed..

Line 85 and 87 was not :)

So this is a valid commit.

**Review by jaymo1011 — APPROVED** [review]

**Comment by jaymo1011** [comment]
> > This change was already applied in [c388d2f](https://github.com/extendedmode/extendedmode/commit/c388d2feaded87a381263daf967af423fd1d2c24).
> 
> Line 18 was changed..
> 
> Line 85 and 87 was not :)
> 
> So this is a valid commit.

Yup, thanks for catching this. Approved and merged!

**Pull request merged**
